"""
Module: report.py

Purpose:
Orchestrates core governance capabilities via CLI and reporting logic for report.py.

Responsibilities:
- Handles specific `report.py` domain logic
- Integrates seamlessly with sibling modules
- Adheres strictly to Hephaestus governance constraints

Part of: Hephaestus Governance Engine

PR comment report generator for Sentinel governance results.

Generates a deterministic Markdown string (no timestamps in the body)
suitable for posting as a GitHub PR comment.
"""

from __future__ import annotations

from typing import Any


def build_pr_comment(results: list[dict[str, Any]]) -> str:
    """Generate a Markdown PR comment body from Sentinel results.

    The output is deterministic: given the same *results*, the same
    string is always produced (no timestamps, no random ids).

    Args:
        results: List of per-entity result dicts, each containing:
            - ``entity_fqn`` (str)
            - ``fgs`` (dict with ``score``, ``compliance_score``,
              ``blast_penalty``, ``blast_radius``, ``is_blocked``,
              ``explanation``)
            - ``drift`` (dict with ``similarity``, ``is_drift``,
              ``threshold``) — optional
            - ``change_magnitude`` (dict with ``magnitude``, ``summary``)
              — optional
            - ``skills_findings`` (list of dicts) — optional

    Returns:
        A Markdown-formatted string ready for use as a PR comment body.
    """
    lines: list[str] = []
    lines.append("## 🔨 Hephaestus Sentinel Report")
    lines.append("")

    any_blocked = False

    for result in results:
        fqn = result.get("entity_fqn", "unknown")
        fgs = result.get("fgs", {})
        drift = result.get("drift")
        change = result.get("change_magnitude")
        skills = result.get("skills_findings", [])

        score = fgs.get("score", 0.0)
        is_blocked = fgs.get("is_blocked", False)
        if is_blocked:
            any_blocked = True

        # FGS status emoji.
        if is_blocked:
            emoji = "🔴"
        elif score < 0.8:
            emoji = "🟡"
        else:
            emoji = "🟢"

        lines.append(f"### {emoji} `{fqn}`")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| **FGS Score** | `{score:.2f}` |")
        lines.append(
            f"| **Compliance** | `{fgs.get('compliance_score', 0.0):.2f}` |"
        )
        lines.append(
            f"| **Blast Penalty** | `{fgs.get('blast_penalty', 0.0):.2f}` |"
        )
        lines.append(
            f"| **Blast Radius (R_blast)** | `{fgs.get('blast_radius', 0)}` |"
        )
        lines.append(
            f"| **Verdict** | **{'BLOCKED' if is_blocked else 'PASSED'}** |"
        )
        lines.append("")

        # Drift section.
        if drift is not None:
            drift_emoji = "⚠️" if drift.get("is_drift", False) else "✅"
            lines.append(
                f"**Semantic Drift:** {drift_emoji} "
                f"similarity=`{drift.get('similarity', 0.0):.4f}` "
                f"(threshold: `{drift.get('threshold', 0.85):.2f}`)"
            )
            lines.append("")

        # Change magnitude section.
        if change is not None:
            lines.append(
                f"**Change Magnitude:** `{change.get('magnitude', 0.0):.4f}` — "
                f"{change.get('summary', '')}"
            )
            lines.append("")

        # Skills findings.
        if skills:
            lines.append("**Skills Findings:**")
            lines.append("")
            for finding in skills:
                skill_name = finding.get("skill", "unknown")
                finding_data = finding.get("result", {})
                lines.append(f"- **{skill_name}**: `{_compact(finding_data)}`")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Final verdict.
    if any_blocked:
        lines.append("### 🚫 Final Verdict: **BLOCKED**")
        lines.append("")
        lines.append(
            "One or more entities failed the Forge Governance Score threshold. "
            "Please address the compliance issues above before merging."
        )
    else:
        lines.append("### ✅ Final Verdict: **PASSED**")
        lines.append("")
        lines.append("All entities meet the governance threshold. Safe to merge.")

    lines.append("")
    lines.append(
        "*Report generated by [Hephaestus Sentinel](https://github.com/hephaestus)*"
    )

    return "\n".join(lines)


def _compact(data: Any, max_len: int = 120) -> str:
    """Return a compact string representation, truncated if necessary."""
    text = str(data)
    if len(text) > max_len:
        return text[: max_len - 3] + "..."
    return text

